/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/TelaLogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/relatorio` | `/relatorio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alerts` | `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `/context/EntregaContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/action-control` | `/action-control`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/monitoring` | `/monitoring`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/TelaLogin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/relatorio` | `/relatorio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/alerts` | `/alerts`; params?: Router.UnknownOutputParams; } | { pathname: `/context/EntregaContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/action-control` | `/action-control`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/monitoring` | `/monitoring`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/TelaLogin${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/relatorio${`?${string}` | `#${string}` | ''}` | `/relatorio${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/alerts${`?${string}` | `#${string}` | ''}` | `/alerts${`?${string}` | `#${string}` | ''}` | `/context/EntregaContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/action-control${`?${string}` | `#${string}` | ''}` | `/action-control${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/monitoring${`?${string}` | `#${string}` | ''}` | `/monitoring${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/TelaLogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/relatorio` | `/relatorio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alerts` | `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `/context/EntregaContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/action-control` | `/action-control`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/monitoring` | `/monitoring`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; };
    }
  }
}
